version: 0.2
env:
  variables:
    APP_NAME: "parkville-info"
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo install process srarted
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --prod
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'